### ISSUE TITLE
v4.0.0-alpha.5 publish list

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-bootstrap#55]
### Highlights

- [ ] update grid structure to [flexbox](http://v4-alpha.getbootstrap.com/getting-started/flexbox/)
- [ ] apply new `blockstack-uikit` btn styles
- [ ] apply new typography styles (p,h1,h2,h3,h4,h5,h6,etc.)
- [ ] apply new spacing items created for v4.0.0-alpha.5
- [ ] apply new `blockstack-uikit` inverse form designs
- [ ] apply new `blockstack-uikit` standard form designs
- [ ] update navbars to utilize new spacing items
- [ ] review `utilities` classes
- [ ] apply new .h-100 (height:100%) utility class to hero
- [ ] confirm consistency in `transition` times (0.2s)
- [ ] apply new `blockstack-uikit`dropdown design
- [ ] apply new `blockstack-uikit` card design

### Tasks

- [ ] https://github.com/blockstack/blockstack-bootstrap/issues/62: Colors
  - https://github.com/blockstack/designs/issues/65
  - [Blockstack Brand](https://projects.invisionapp.com/boards/HE2VVROFSGB27/))
- [ ] : Options (See )
- [ ] https://github.com/blockstack/blockstack-bootstrap/issues/65: Spacing
- [ ] : Body
5. links
6. grid breakpoints
7. grid containers
8. grid columns
9. fonts
10. components
11. tables
12. buttons
13. forms
14. dropdowns
15. z-index master list
16. navbar
17. navs
18. pagination
19. jumbotron
20. form states and alerts
21. cards
22. tooltips
23. popovers
24. tags
25. modals
26. alerts
27. progress bars
28. list group
29. image thumbnails
30. figures
31. breadcrumbs
32. media objects
33. carousel
34. close
35. code
