### ISSUE TITLE
diff-merge all _custom-*.scss files with latest v4-alpha5

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-bootstrap#64]
`diff-merge` all `_custom-*.scss` files with the latest bootstrap merge of v4-alpha5 to avoid breakage.

**Core variables**
- [x] @import "custom"
- [x] @import "custom-variables"
  - [ ] update all spacing variables in _custom-variables https://github.com/blockstack/blockstack-bootstrap/issues/65
  - [ ] review all breakpoints and containers in _custom-variables https://github.com/blockstack/blockstack-bootstrap/issues/66
- [x] @import "custom-reboot"
- [x] @import "custom-type"
- [x] @import "custom-tables"
- [x] @import "custom-buttons"
- [x] @import "custom-nav"
- [x] @import "custom-card
- [x] @import "custom-pagination"

**Mixins**
- [x] @import "mixins/custom-mixins"
- [x] @import "mixins/gradients"

**Utilities**
- [x] @import "utilities/custom-background"

**Comment by guylepage3** [comment]
complete.
- @import "custom-reboot"
- @import "custom-variables"

**items yet to resolve in `_custom-variables.scss`**
- [ ] update all spacing variables in _custom-variables https://github.com/blockstack/blockstack-bootstrap/issues/65
- [ ] review all breakpoints and containers in _custom-variables https://github.com/blockstack/blockstack-bootstrap/issues/66

**Comment by guylepage3** [comment]
complete.
- @import "custom"
- @import "custom-type"
- @import "custom-tables"
- @import "custom-buttons"

**Comment by guylepage3** [comment]
complete.
- @import "custom-nav"
- @import "custom-card"
- @import "custom-pagination"
- @import "mixins/custom-mixins" No merge needed as it's just a new imported mixin file
- @import "mixins/gradients"
- @import "utilities/custom-background"
